#if UNITY_EDITOR
using System.IO;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

namespace Logging.Editor
{
    [InitializeOnLoad]
    public static class LogEnumGenerator
    {
        private const string GeneratedDir = "Assets/Logging/Generated";
        internal const string GeneratedFileName = "LogChannels.generated.cs";
        private const string GeneratedPath = GeneratedDir + "/" + GeneratedFileName;
        private static bool _pendingOnce;

        static LogEnumGenerator()
        {
            // One-time, idempotent generation after domain reload
            EditorApplication.delayCall += () =>
            {
                if (_pendingOnce) return;
                _pendingOnce = true;
                TryGenerate();
            };
        }

        [MenuItem("Tools/Logging/Rebuild LogChannels Enum")]
        public static void RebuildMenu() => TryGenerate(true);

        public static void TryGenerate(bool force = false)
        {
            // Do NOT call LogConfig.Instance here; avoid creating assets and refresh loops
            var cfg = Resources.Load<Logging.LogConfig>("LogConfig");
            if (!cfg) return;

            // Ensure IDs exist (in-memory only)
            foreach (var c in cfg.channels) c.EnsureId();

            var newContent = BuildEnumContent(cfg);
            Directory.CreateDirectory(GeneratedDir);

            string oldContent = null;
            if (File.Exists(GeneratedPath))
            {
                try { oldContent = File.ReadAllText(GeneratedPath); } catch { }
            }

            if (!force && oldContent == newContent) return; // no-op prevents endless recompiles

            File.WriteAllText(GeneratedPath, newContent, Encoding.UTF8);
            AssetDatabase.ImportAsset(GeneratedPath, ImportAssetOptions.ForceSynchronousImport);
        }

        private static string BuildEnumContent(Logging.LogConfig cfg)
        {
            var sb = new StringBuilder(1024);
            sb.AppendLine("// Auto-generated by LogEnumGenerator. Do not edit.");
            sb.AppendLine("namespace Logging {");
            sb.AppendLine("    public enum LogChannels : int");
            sb.AppendLine("    {");

            // Track used member names (case-insensitive) to avoid duplicates
            var taken = new HashSet<string>(System.StringComparer.OrdinalIgnoreCase);

            int index = 0;
            foreach (var c in cfg.channels.Where(x => x != null && !string.IsNullOrWhiteSpace(x.name)))
            {
                var baseName = Sanitize(c.name);
                var unique = MakeUnique(baseName, taken); // Appends _1, _2... if needed
                sb.AppendLine($"        {unique} = {index},");
                index++;
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string MakeUnique(string baseName, HashSet<string> taken)
        {
            var name = baseName;
            int i = 1;
            while (taken.Contains(name))
            {
                name = $"{baseName}_{i}";
                i++;
            }
            taken.Add(name);
            return name;
        }

        private static string Sanitize(string name)
        {
            if (string.IsNullOrEmpty(name)) return "Channel";

            // Replace non-identifier chars with underscores
            var filtered = new string(name.Select(ch => char.IsLetterOrDigit(ch) ? ch : '_').ToArray());
            if (string.IsNullOrEmpty(filtered)) filtered = "Channel";

            // Must start with letter or underscore
            if (!char.IsLetter(filtered[0]) && filtered[0] != '_')
                filtered = "_" + filtered;

            // Avoid C# keywords by prefixing underscore if needed
            if (CSharpKeywords.Contains(filtered))
                filtered = "_" + filtered;

            return filtered;
        }

        private static readonly HashSet<string> CSharpKeywords = new HashSet<string>(new[]
        {
            "abstract","as","base","bool","break","byte","case","catch","char","checked","class","const","continue",
            "decimal","default","delegate","do","double","else","enum","event","explicit","extern","false","finally",
            "fixed","float","for","foreach","goto","if","implicit","in","int","interface","internal","is","lock",
            "long","namespace","new","null","object","operator","out","override","params","private","protected",
            "public","readonly","ref","return","sbyte","sealed","short","sizeof","stackalloc","static","string",
            "struct","switch","this","throw","true","try","typeof","uint","ulong","unchecked","unsafe","ushort",
            "using","virtual","void","volatile","while","add","alias","async","await","dynamic","from","get","global",
            "group","into","join","let","orderby","partial","remove","select","set","value","var","where","yield",
            "when","record","init","nint","nuint","file","required"
        }, System.StringComparer.Ordinal);
    }

    // Optional: Only trigger a rebuild when LogConfig.asset changes (idempotent write prevents loops)
    public class LogConfigChangeWatcher : AssetPostprocessor
    {
        static void OnPostprocessAllAssets(string[] importedAssets, string[] deletedAssets, string[] movedAssets, string[] movedFromAssetPaths)
        {
            if (importedAssets.Any(p => p.EndsWith(LogEnumGenerator.GeneratedFileName))) return;
            if (importedAssets.Any(p => p.EndsWith("LogConfig.asset")))
                LogEnumGenerator.TryGenerate();
        }
    }
}
#endif